// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyO8iY_anzj2F70CRN6PCj_CB6_EqEizc',
    appId: '1:314578788821:web:662b4051e8244aaaa49d5c',
    messagingSenderId: '314578788821',
    projectId: 'calendar-f489f',
    authDomain: 'calendar-f489f.firebaseapp.com',
    storageBucket: 'calendar-f489f.appspot.com',
    measurementId: 'G-5F3Z0B5N20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9TUhIEOm47oAsrwlPAVJMKyn2ebqd9vQ',
    appId: '1:314578788821:android:05f4a1ecf1c310d8a49d5c',
    messagingSenderId: '314578788821',
    projectId: 'calendar-f489f',
    storageBucket: 'calendar-f489f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuMRoOZlIW1qVrKZCg9zlEU-VfvRw8UyA',
    appId: '1:314578788821:ios:384d42e1639f036ba49d5c',
    messagingSenderId: '314578788821',
    projectId: 'calendar-f489f',
    storageBucket: 'calendar-f489f.appspot.com',
    androidClientId: '314578788821-v9mgf8ke3b04ac0l31ettmdq1lau159g.apps.googleusercontent.com',
    iosClientId: '314578788821-knq43i9q6sorfo7a05gu75clkt97hprr.apps.googleusercontent.com',
    iosBundleId: 'com.example.calendarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuMRoOZlIW1qVrKZCg9zlEU-VfvRw8UyA',
    appId: '1:314578788821:ios:384d42e1639f036ba49d5c',
    messagingSenderId: '314578788821',
    projectId: 'calendar-f489f',
    storageBucket: 'calendar-f489f.appspot.com',
    androidClientId: '314578788821-v9mgf8ke3b04ac0l31ettmdq1lau159g.apps.googleusercontent.com',
    iosClientId: '314578788821-knq43i9q6sorfo7a05gu75clkt97hprr.apps.googleusercontent.com',
    iosBundleId: 'com.example.calendarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyO8iY_anzj2F70CRN6PCj_CB6_EqEizc',
    appId: '1:314578788821:web:2a4913f8bc8334a3a49d5c',
    messagingSenderId: '314578788821',
    projectId: 'calendar-f489f',
    authDomain: 'calendar-f489f.firebaseapp.com',
    storageBucket: 'calendar-f489f.appspot.com',
    measurementId: 'G-ECQ751QNQ2',
  );
}
